# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

# Enable C++ support
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# Enable GPIO
CONFIG_GPIO=y

# Enable software debounce
#CONFIG_GPIO_DEBOUNCE=y
#CONFIG_GPIO_DEBOUNCE_TIME_MS=50

# Enable workqueue
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# Enable zbus
CONFIG_ZBUS=y
CONFIG_ZBUS_LOG_LEVEL_INF=y
CONFIG_ZBUS_CHANNEL_NAME=y
CONFIG_ZBUS_OBSERVER_NAME=y
CONFIG_ZBUS_RUNTIME_OBSERVERS=y


# Enable logging
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_MAIN_THREAD_PRIORITY=5

CONFIG_BOOT_BANNER=n
CONFIG_ASSERT=y

